[profile.dev]
opt-level = 0

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"

[workspace]
members = [
  "crates/diesel-connection",
  "crates/derive-diesel-connection",
]
resolver = "2"
